apiVersion: batch/v1
kind: Job
metadata:
  name: copyexplorerconfigs
spec:
  backoffLimit: 1
  template:
    metadata:
      name: copyexplorerconfigs
    spec:
      restartPolicy: "Never"
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: filepvc
      
      containers:
      - name: copyartifacts
        image: alpine:3.7
        imagePullPolicy: Always
        command: ["sh", "-c", "ls -l /shared; rm -rf /shared/explorer; ls -l /shared; while [ ! -d /shared/explorer ]; do echo Waiting for artifacts to be copied; sleep 2; done; sleep 10; ls -l /shared/artifacts; "]
        volumeMounts:
        - mountPath: /shared
          name: myvolume