apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperledger-explorer-app
  labels: 
    app: hyperledger-explorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-explorer-app
  template:
    metadata:
      labels:
        app: hyperledger-explorer-app
    spec:
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: filepvc

      containers:
      - name: explorer
        image: hyperledger/explorer:latest
        command: ["sh" , "-c" , "sleep 3000;"]
        env:
        - name: TZ
          value: "Europe/Istanbul"
        - name: DATABASE_HOST
          value: hyperledger-explorer-db
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /shared
          name: myvolume